2023-01-04 11:20:17.223246: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-04 11:20:21.481222: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-04 11:20:39.787647: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib64:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/mpfr-4.1.0-4owr5jskgrebkppacvwkfa7tdtlqjalg/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/gmp-6.2.1-rg3gv5myy7lt46cjxvmdmsghhyhxguqo/lib:/work/FAC/FBM/DMF/smartin/cellfusion/wanlan/miniconda3/envs/tf210/lib/
2023-01-04 11:20:39.787773: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib64:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/mpfr-4.1.0-4owr5jskgrebkppacvwkfa7tdtlqjalg/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/gmp-6.2.1-rg3gv5myy7lt46cjxvmdmsghhyhxguqo/lib:/work/FAC/FBM/DMF/smartin/cellfusion/wanlan/miniconda3/envs/tf210/lib/
2023-01-04 11:20:39.787785: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
I0104 11:21:06.066428 139897736877696 run_model_training.py:65] Reading the config file.
I0104 11:21:06.081599 139897736877696 run_model_training.py:71] Starting the experiment.
2023-01-04 11:21:06.083141: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-04 11:21:10.542460: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38224 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:21:00.0, compute capability: 8.0
2023-01-04 11:21:10.544784: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 38224 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:e2:00.0, compute capability: 8.0
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0104 11:21:11.192508 139897736877696 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I0104 11:21:11.201320 139897736877696 deeplab.py:58] Synchronized Batchnorm is used.
I0104 11:21:11.202114 139897736877696 axial_resnet_instances.py:144] Axial-ResNet final config: {'num_blocks': [3, 6, 3, 3], 'backbone_layer_multiplier': 4.5, 'width_multiplier': 1, 'stem_width_multiplier': 1, 'output_stride': 16, 'classification_mode': True, 'backbone_type': 'wider_resnet', 'use_axial_beyond_stride': 16, 'backbone_use_transformer_beyond_stride': 0, 'extra_decoder_use_transformer_beyond_stride': 32, 'backbone_decoder_num_stacks': 0, 'backbone_decoder_blocks_per_stage': 1, 'extra_decoder_num_stacks': 0, 'extra_decoder_blocks_per_stage': 1, 'max_num_mask_slots': 128, 'num_mask_slots': 128, 'memory_channels': 256, 'base_transformer_expansion': 1.0, 'global_feed_forward_network_channels': 256, 'high_resolution_output_stride': 4, 'activation': 'relu', 'block_group_config': {'attention_bottleneck_expansion': 4, 'drop_path_keep_prob': 0.8, 'drop_path_beyond_stride': 4, 'drop_path_schedule': 'linear', 'positional_encoding_type': None, 'use_global_beyond_stride': 0, 'use_sac_beyond_stride': 0, 'use_squeeze_and_excite': False, 'conv_use_recompute_grad': True, 'axial_use_recompute_grad': True, 'recompute_within_stride': 0, 'transformer_use_recompute_grad': False, 'axial_layer_config': {'query_shape': (129, 129), 'key_expansion': 2, 'value_expansion': 4, 'memory_flange': (32, 32), 'double_global_attention': False, 'num_heads': 8, 'use_query_rpe_similarity': True, 'use_key_rpe_similarity': True, 'use_content_similarity': True, 'retrieve_value_rpe': True, 'retrieve_value_content': True, 'initialization_std_for_query_key_rpe': 1.0, 'initialization_std_for_value_rpe': 1.0, 'self_attention_activation': 'softmax'}, 'dual_path_transformer_layer_config': {'num_heads': 8, 'bottleneck_expansion': 2, 'key_expansion': 1, 'value_expansion': 2, 'feed_forward_network_channels': 2048, 'use_memory_self_attention': True, 'use_pixel2memory_feedback_attention': True, 'transformer_activation': 'softmax'}}, 'bn_layer': functools.partial(<class 'keras.layers.normalization.batch_normalization.SyncBatchNormalization'>, momentum=0.99, epsilon=0.001), 'conv_kernel_weight_decay': 0.0}
I0104 11:21:11.677907 139897736877696 deeplab.py:97] Setting pooling size to (33, 33)
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.017753 139897736877696 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.020708 139897736877696 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.022630 139897736877696 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.023198 139897736877696 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.025489 139897736877696 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.026044 139897736877696 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.027520 139897736877696 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.028071 139897736877696 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.030249 139897736877696 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.030789 139897736877696 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I0104 11:21:17.076891 139897736877696 controller.py:391] restoring or initializing model...
I0104 11:21:17.261673 139897736877696 controller.py:395] restored model from ../model_dir/deepyeast_001/ckpt-80000.
I0104 11:21:17.261814 139897736877696 controller.py:217] restored from checkpoint: ../model_dir/deepyeast_001/ckpt-80000
I0104 11:21:17.262023 139897736877696 controller.py:236] train | step:  80000 | training until step 100000...
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0104 11:21:18.808683 139897736877696 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0104 11:21:18.851703 139897736877696 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0104 11:21:18.865999 139897736877696 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0104 11:21:19.938698 139897736877696 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0104 11:21:19.953159 139897736877696 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0104 11:21:19.967231 139897736877696 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0104 11:21:20.072602 139897736877696 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0104 11:21:20.087368 139897736877696 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0104 11:21:20.101516 139897736877696 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I0104 11:21:20.201847 139897736877696 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
2023-01-04 11:30:39.083327: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8401
2023-01-04 11:30:39.376222: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8401
2023-01-04 11:30:47.541128: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2023-01-04 11:30:48.396832: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
W0104 11:42:04.345540 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 80000, expected updated value to be 80100, but it was 80200.
I0104 11:42:04.354314 139897736877696 controller.py:457] train | step:  80200 | steps/sec:    0.2 | output: 
    {'learning_rate': 7.915487e-08,
     'losses/train_center_loss': 0.55113554,
     'losses/train_regression_loss': 0.91353065,
     'losses/train_semantic_loss': 1.9402366,
     'losses/train_total_loss': 3.404903}
W0104 11:53:05.231791 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 80200, expected updated value to be 80300, but it was 80400.
I0104 11:53:05.232755 139897736877696 controller.py:457] train | step:  80400 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.84349e-08,
     'losses/train_center_loss': 0.5650811,
     'losses/train_regression_loss': 0.92455107,
     'losses/train_semantic_loss': 1.9896305,
     'losses/train_total_loss': 3.4792626}
W0104 12:04:03.555712 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 80400, expected updated value to be 80500, but it was 80600.
I0104 12:04:03.556670 139897736877696 controller.py:457] train | step:  80600 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.771422e-08,
     'losses/train_center_loss': 0.5456248,
     'losses/train_regression_loss': 0.92333376,
     'losses/train_semantic_loss': 2.020133,
     'losses/train_total_loss': 3.4890912}
W0104 12:15:03.732667 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 80600, expected updated value to be 80700, but it was 80800.
I0104 12:15:03.733667 139897736877696 controller.py:457] train | step:  80800 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.699278e-08,
     'losses/train_center_loss': 0.56336707,
     'losses/train_regression_loss': 0.9283824,
     'losses/train_semantic_loss': 1.9794894,
     'losses/train_total_loss': 3.471239}
W0104 12:26:04.257827 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 80800, expected updated value to be 80900, but it was 81000.
I0104 12:26:04.258793 139897736877696 controller.py:457] train | step:  81000 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.6270595e-08,
     'losses/train_center_loss': 0.55654526,
     'losses/train_regression_loss': 0.9259361,
     'losses/train_semantic_loss': 2.0230408,
     'losses/train_total_loss': 3.5055215}
I0104 12:26:13.735643 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-81000.
W0104 12:37:12.186776 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 81000, expected updated value to be 81100, but it was 81200.
I0104 12:37:12.187785 139897736877696 controller.py:457] train | step:  81200 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.554767e-08,
     'losses/train_center_loss': 0.5663107,
     'losses/train_regression_loss': 0.9211551,
     'losses/train_semantic_loss': 1.9698242,
     'losses/train_total_loss': 3.4572897}
W0104 12:48:11.959943 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 81200, expected updated value to be 81300, but it was 81400.
I0104 12:48:11.960751 139897736877696 controller.py:457] train | step:  81400 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.4823944e-08,
     'losses/train_center_loss': 0.5928894,
     'losses/train_regression_loss': 0.9275889,
     'losses/train_semantic_loss': 2.0109751,
     'losses/train_total_loss': 3.5314536}
W0104 12:59:11.735112 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 81400, expected updated value to be 81500, but it was 81600.
I0104 12:59:11.749949 139897736877696 controller.py:457] train | step:  81600 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.4099454e-08,
     'losses/train_center_loss': 0.5754802,
     'losses/train_regression_loss': 0.9272109,
     'losses/train_semantic_loss': 2.0198493,
     'losses/train_total_loss': 3.52254}
W0104 13:10:11.975136 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 81600, expected updated value to be 81700, but it was 81800.
I0104 13:10:11.975955 139897736877696 controller.py:457] train | step:  81800 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.337417e-08,
     'losses/train_center_loss': 0.5666397,
     'losses/train_regression_loss': 0.9224213,
     'losses/train_semantic_loss': 2.0107856,
     'losses/train_total_loss': 3.4998467}
W0104 13:21:10.878086 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 81800, expected updated value to be 81900, but it was 82000.
I0104 13:21:10.879077 139897736877696 controller.py:457] train | step:  82000 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.26481e-08,
     'losses/train_center_loss': 0.55670965,
     'losses/train_regression_loss': 0.9271742,
     'losses/train_semantic_loss': 2.0250585,
     'losses/train_total_loss': 3.5089424}
I0104 13:21:19.550786 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-82000.
W0104 13:32:19.519361 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 82000, expected updated value to be 82100, but it was 82200.
I0104 13:32:19.520199 139897736877696 controller.py:457] train | step:  82200 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.192119e-08,
     'losses/train_center_loss': 0.56388,
     'losses/train_regression_loss': 0.9158579,
     'losses/train_semantic_loss': 2.0086188,
     'losses/train_total_loss': 3.4883556}
W0104 13:43:22.342193 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 82200, expected updated value to be 82300, but it was 82400.
I0104 13:43:22.342999 139897736877696 controller.py:457] train | step:  82400 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.11935e-08,
     'losses/train_center_loss': 0.55087453,
     'losses/train_regression_loss': 0.9201353,
     'losses/train_semantic_loss': 1.9857733,
     'losses/train_total_loss': 3.4567835}
W0104 13:54:20.517451 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 82400, expected updated value to be 82500, but it was 82600.
I0104 13:54:20.518319 139897736877696 controller.py:457] train | step:  82600 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.0464985e-08,
     'losses/train_center_loss': 0.5538685,
     'losses/train_regression_loss': 0.9178131,
     'losses/train_semantic_loss': 1.9820486,
     'losses/train_total_loss': 3.4537299}
W0104 14:05:22.333926 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 82600, expected updated value to be 82700, but it was 82800.
I0104 14:05:22.334781 139897736877696 controller.py:457] train | step:  82800 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.97356e-08,
     'losses/train_center_loss': 0.5486247,
     'losses/train_regression_loss': 0.9148412,
     'losses/train_semantic_loss': 1.9852414,
     'losses/train_total_loss': 3.4487078}
W0104 14:16:26.302336 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 82800, expected updated value to be 82900, but it was 83000.
I0104 14:16:26.303290 139897736877696 controller.py:457] train | step:  83000 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.90054e-08,
     'losses/train_center_loss': 0.5707736,
     'losses/train_regression_loss': 0.9214219,
     'losses/train_semantic_loss': 2.0229304,
     'losses/train_total_loss': 3.5151262}
I0104 14:16:34.513167 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-83000.
W0104 14:27:34.225767 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 83000, expected updated value to be 83100, but it was 83200.
I0104 14:27:34.226578 139897736877696 controller.py:457] train | step:  83200 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.8274296e-08,
     'losses/train_center_loss': 0.5575626,
     'losses/train_regression_loss': 0.9149469,
     'losses/train_semantic_loss': 2.0151734,
     'losses/train_total_loss': 3.487683}
W0104 14:38:37.897629 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 83200, expected updated value to be 83300, but it was 83400.
I0104 14:38:37.898470 139897736877696 controller.py:457] train | step:  83400 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.7542366e-08,
     'losses/train_center_loss': 0.567611,
     'losses/train_regression_loss': 0.92385995,
     'losses/train_semantic_loss': 2.0167565,
     'losses/train_total_loss': 3.508228}
W0104 14:49:41.009778 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 83400, expected updated value to be 83500, but it was 83600.
I0104 14:49:41.010587 139897736877696 controller.py:457] train | step:  83600 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.680951e-08,
     'losses/train_center_loss': 0.5736423,
     'losses/train_regression_loss': 0.9256016,
     'losses/train_semantic_loss': 1.9834975,
     'losses/train_total_loss': 3.482741}
W0104 15:00:43.143930 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 83600, expected updated value to be 83700, but it was 83800.
I0104 15:00:43.144777 139897736877696 controller.py:457] train | step:  83800 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.607581e-08,
     'losses/train_center_loss': 0.56240284,
     'losses/train_regression_loss': 0.9235944,
     'losses/train_semantic_loss': 2.0015717,
     'losses/train_total_loss': 3.4875693}
W0104 15:11:44.648498 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 83800, expected updated value to be 83900, but it was 84000.
I0104 15:11:44.649444 139897736877696 controller.py:457] train | step:  84000 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.534118e-08,
     'losses/train_center_loss': 0.54976225,
     'losses/train_regression_loss': 0.92225504,
     'losses/train_semantic_loss': 2.0168843,
     'losses/train_total_loss': 3.4889014}
I0104 15:11:52.933362 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-84000.
W0104 15:22:53.316250 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 84000, expected updated value to be 84100, but it was 84200.
I0104 15:22:53.317048 139897736877696 controller.py:457] train | step:  84200 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.4605615e-08,
     'losses/train_center_loss': 0.561638,
     'losses/train_regression_loss': 0.9199582,
     'losses/train_semantic_loss': 2.0011923,
     'losses/train_total_loss': 3.4827883}
W0104 15:33:55.502517 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 84200, expected updated value to be 84300, but it was 84400.
I0104 15:33:55.503322 139897736877696 controller.py:457] train | step:  84400 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.386915e-08,
     'losses/train_center_loss': 0.56508636,
     'losses/train_regression_loss': 0.92760164,
     'losses/train_semantic_loss': 2.0231469,
     'losses/train_total_loss': 3.5158346}
W0104 15:44:56.324064 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 84400, expected updated value to be 84500, but it was 84600.
I0104 15:44:56.324914 139897736877696 controller.py:457] train | step:  84600 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.3131715e-08,
     'losses/train_center_loss': 0.5607125,
     'losses/train_regression_loss': 0.9195694,
     'losses/train_semantic_loss': 2.0060565,
     'losses/train_total_loss': 3.4863386}
W0104 15:55:55.874490 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 84600, expected updated value to be 84700, but it was 84800.
I0104 15:55:55.875313 139897736877696 controller.py:457] train | step:  84800 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.239334e-08,
     'losses/train_center_loss': 0.56305736,
     'losses/train_regression_loss': 0.9260423,
     'losses/train_semantic_loss': 2.0199144,
     'losses/train_total_loss': 3.5090148}
W0104 16:06:56.252646 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 84800, expected updated value to be 84900, but it was 85000.
I0104 16:06:56.253464 139897736877696 controller.py:457] train | step:  85000 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.1653964e-08,
     'losses/train_center_loss': 0.5584407,
     'losses/train_regression_loss': 0.92048883,
     'losses/train_semantic_loss': 1.9720005,
     'losses/train_total_loss': 3.45093}
I0104 16:07:04.170200 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-85000.
W0104 16:18:07.732877 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 85000, expected updated value to be 85100, but it was 85200.
I0104 16:18:07.733696 139897736877696 controller.py:457] train | step:  85200 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.0913635e-08,
     'losses/train_center_loss': 0.5602606,
     'losses/train_regression_loss': 0.92807037,
     'losses/train_semantic_loss': 2.0278916,
     'losses/train_total_loss': 3.5162225}
W0104 16:29:06.237792 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 85200, expected updated value to be 85300, but it was 85400.
I0104 16:29:06.238767 139897736877696 controller.py:457] train | step:  85400 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.01723e-08,
     'losses/train_center_loss': 0.5502714,
     'losses/train_regression_loss': 0.9159898,
     'losses/train_semantic_loss': 1.9980136,
     'losses/train_total_loss': 3.4642756}
W0104 16:40:08.039078 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 85400, expected updated value to be 85500, but it was 85600.
I0104 16:40:08.039880 139897736877696 controller.py:457] train | step:  85600 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.9429922e-08,
     'losses/train_center_loss': 0.553965,
     'losses/train_regression_loss': 0.91955304,
     'losses/train_semantic_loss': 2.0114884,
     'losses/train_total_loss': 3.4850068}
W0104 16:51:12.761026 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 85600, expected updated value to be 85700, but it was 85800.
I0104 16:51:12.761829 139897736877696 controller.py:457] train | step:  85800 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.8686542e-08,
     'losses/train_center_loss': 0.5488001,
     'losses/train_regression_loss': 0.91743904,
     'losses/train_semantic_loss': 1.9657397,
     'losses/train_total_loss': 3.4319787}
W0104 17:02:16.489677 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 85800, expected updated value to be 85900, but it was 86000.
I0104 17:02:16.490509 139897736877696 controller.py:457] train | step:  86000 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.794209e-08,
     'losses/train_center_loss': 0.55761564,
     'losses/train_regression_loss': 0.91917235,
     'losses/train_semantic_loss': 2.0149071,
     'losses/train_total_loss': 3.4916956}
I0104 17:02:24.135912 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-86000.
W0104 17:13:23.125003 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 86000, expected updated value to be 86100, but it was 86200.
I0104 17:13:23.133073 139897736877696 controller.py:457] train | step:  86200 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.7196594e-08,
     'losses/train_center_loss': 0.5727068,
     'losses/train_regression_loss': 0.9244202,
     'losses/train_semantic_loss': 1.9969476,
     'losses/train_total_loss': 3.4940743}
W0104 17:24:24.940436 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 86200, expected updated value to be 86300, but it was 86400.
I0104 17:24:24.941243 139897736877696 controller.py:457] train | step:  86400 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.6449995e-08,
     'losses/train_center_loss': 0.5654376,
     'losses/train_regression_loss': 0.9161334,
     'losses/train_semantic_loss': 1.9892027,
     'losses/train_total_loss': 3.470774}
W0104 17:35:28.494269 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 86400, expected updated value to be 86500, but it was 86600.
I0104 17:35:28.495092 139897736877696 controller.py:457] train | step:  86600 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.570232e-08,
     'losses/train_center_loss': 0.56806207,
     'losses/train_regression_loss': 0.929666,
     'losses/train_semantic_loss': 2.0276983,
     'losses/train_total_loss': 3.5254264}
W0104 17:46:29.022152 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 86600, expected updated value to be 86700, but it was 86800.
I0104 17:46:29.023019 139897736877696 controller.py:457] train | step:  86800 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.495353e-08,
     'losses/train_center_loss': 0.56698483,
     'losses/train_regression_loss': 0.9229263,
     'losses/train_semantic_loss': 1.994642,
     'losses/train_total_loss': 3.4845533}
W0104 17:57:28.725795 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 86800, expected updated value to be 86900, but it was 87000.
I0104 17:57:28.726735 139897736877696 controller.py:457] train | step:  87000 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.420358e-08,
     'losses/train_center_loss': 0.5538252,
     'losses/train_regression_loss': 0.9197237,
     'losses/train_semantic_loss': 2.00491,
     'losses/train_total_loss': 3.4784586}
I0104 17:57:36.767571 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-87000.
W0104 18:08:37.481095 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 87000, expected updated value to be 87100, but it was 87200.
I0104 18:08:37.481918 139897736877696 controller.py:457] train | step:  87200 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.34525e-08,
     'losses/train_center_loss': 0.56033,
     'losses/train_regression_loss': 0.92111,
     'losses/train_semantic_loss': 1.9929914,
     'losses/train_total_loss': 3.4744308}
W0104 18:19:36.193463 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 87200, expected updated value to be 87300, but it was 87400.
I0104 18:19:36.194270 139897736877696 controller.py:457] train | step:  87400 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.2700216e-08,
     'losses/train_center_loss': 0.55158406,
     'losses/train_regression_loss': 0.92028046,
     'losses/train_semantic_loss': 1.9816763,
     'losses/train_total_loss': 3.4535413}
W0104 18:30:35.684929 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 87400, expected updated value to be 87500, but it was 87600.
I0104 18:30:35.685731 139897736877696 controller.py:457] train | step:  87600 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.194677e-08,
     'losses/train_center_loss': 0.56822187,
     'losses/train_regression_loss': 0.9192856,
     'losses/train_semantic_loss': 2.0054896,
     'losses/train_total_loss': 3.4929972}
W0104 18:41:36.886929 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 87600, expected updated value to be 87700, but it was 87800.
I0104 18:41:36.887725 139897736877696 controller.py:457] train | step:  87800 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.119207e-08,
     'losses/train_center_loss': 0.5502752,
     'losses/train_regression_loss': 0.9199737,
     'losses/train_semantic_loss': 1.9780967,
     'losses/train_total_loss': 3.4483454}
W0104 18:52:40.201451 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 87800, expected updated value to be 87900, but it was 88000.
I0104 18:52:40.202281 139897736877696 controller.py:457] train | step:  88000 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.0436174e-08,
     'losses/train_center_loss': 0.54332274,
     'losses/train_regression_loss': 0.92463744,
     'losses/train_semantic_loss': 2.002474,
     'losses/train_total_loss': 3.4704332}
I0104 18:52:48.541392 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-88000.
W0104 19:03:49.934108 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 88000, expected updated value to be 88100, but it was 88200.
I0104 19:03:49.935034 139897736877696 controller.py:457] train | step:  88200 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.967898e-08,
     'losses/train_center_loss': 0.5517643,
     'losses/train_regression_loss': 0.917578,
     'losses/train_semantic_loss': 1.9845793,
     'losses/train_total_loss': 3.4539218}
W0104 19:14:51.837995 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 88200, expected updated value to be 88300, but it was 88400.
I0104 19:14:51.838784 139897736877696 controller.py:457] train | step:  88400 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.8920526e-08,
     'losses/train_center_loss': 0.5585655,
     'losses/train_regression_loss': 0.9205484,
     'losses/train_semantic_loss': 2.0065045,
     'losses/train_total_loss': 3.4856188}
W0104 19:25:53.227813 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 88400, expected updated value to be 88500, but it was 88600.
I0104 19:25:53.228611 139897736877696 controller.py:457] train | step:  88600 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.8160764e-08,
     'losses/train_center_loss': 0.5492926,
     'losses/train_regression_loss': 0.9234439,
     'losses/train_semantic_loss': 2.0104253,
     'losses/train_total_loss': 3.4831626}
W0104 19:36:53.859639 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 88600, expected updated value to be 88700, but it was 88800.
I0104 19:36:53.860465 139897736877696 controller.py:457] train | step:  88800 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.7399645e-08,
     'losses/train_center_loss': 0.54084426,
     'losses/train_regression_loss': 0.9179497,
     'losses/train_semantic_loss': 1.9793451,
     'losses/train_total_loss': 3.4381387}
W0104 19:47:53.604715 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 88800, expected updated value to be 88900, but it was 89000.
I0104 19:47:53.605564 139897736877696 controller.py:457] train | step:  89000 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.6637194e-08,
     'losses/train_center_loss': 0.5577194,
     'losses/train_regression_loss': 0.91900986,
     'losses/train_semantic_loss': 1.9847761,
     'losses/train_total_loss': 3.4615057}
I0104 19:48:01.530432 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-89000.
W0104 19:58:57.624995 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 89000, expected updated value to be 89100, but it was 89200.
I0104 19:58:57.637766 139897736877696 controller.py:457] train | step:  89200 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.587333e-08,
     'losses/train_center_loss': 0.55664223,
     'losses/train_regression_loss': 0.91543305,
     'losses/train_semantic_loss': 1.9918185,
     'losses/train_total_loss': 3.4638953}
W0104 20:10:01.171084 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 89200, expected updated value to be 89300, but it was 89400.
I0104 20:10:01.172066 139897736877696 controller.py:457] train | step:  89400 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.5108067e-08,
     'losses/train_center_loss': 0.57027686,
     'losses/train_regression_loss': 0.92193377,
     'losses/train_semantic_loss': 2.023389,
     'losses/train_total_loss': 3.5156}
W0104 20:20:59.691000 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 89400, expected updated value to be 89500, but it was 89600.
I0104 20:20:59.691810 139897736877696 controller.py:457] train | step:  89600 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.434135e-08,
     'losses/train_center_loss': 0.5605422,
     'losses/train_regression_loss': 0.92775613,
     'losses/train_semantic_loss': 2.0133798,
     'losses/train_total_loss': 3.5016792}
W0104 20:31:58.872695 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 89600, expected updated value to be 89700, but it was 89800.
I0104 20:31:58.873533 139897736877696 controller.py:457] train | step:  89800 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.357316e-08,
     'losses/train_center_loss': 0.56758225,
     'losses/train_regression_loss': 0.91144705,
     'losses/train_semantic_loss': 1.9822493,
     'losses/train_total_loss': 3.4612787}
W0104 20:43:02.460583 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 89800, expected updated value to be 89900, but it was 90000.
I0104 20:43:02.461387 139897736877696 controller.py:457] train | step:  90000 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.2803485e-08,
     'losses/train_center_loss': 0.54465264,
     'losses/train_regression_loss': 0.91841745,
     'losses/train_semantic_loss': 1.9892355,
     'losses/train_total_loss': 3.4523053}
I0104 20:43:10.427468 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-90000.
W0104 20:54:12.146044 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 90000, expected updated value to be 90100, but it was 90200.
I0104 20:54:12.146872 139897736877696 controller.py:457] train | step:  90200 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.203223e-08,
     'losses/train_center_loss': 0.5400448,
     'losses/train_regression_loss': 0.9127952,
     'losses/train_semantic_loss': 1.9855106,
     'losses/train_total_loss': 3.438351}
W0104 21:05:14.782165 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 90200, expected updated value to be 90300, but it was 90400.
I0104 21:05:14.782973 139897736877696 controller.py:457] train | step:  90400 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.1259423e-08,
     'losses/train_center_loss': 0.54625285,
     'losses/train_regression_loss': 0.9137532,
     'losses/train_semantic_loss': 1.9908527,
     'losses/train_total_loss': 3.450858}
W0104 21:16:16.528320 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 90400, expected updated value to be 90500, but it was 90600.
I0104 21:16:16.529135 139897736877696 controller.py:457] train | step:  90600 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.048498e-08,
     'losses/train_center_loss': 0.5570231,
     'losses/train_regression_loss': 0.9202307,
     'losses/train_semantic_loss': 1.9791958,
     'losses/train_total_loss': 3.4564495}
W0104 21:27:16.936727 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 90600, expected updated value to be 90700, but it was 90800.
I0104 21:27:16.937702 139897736877696 controller.py:457] train | step:  90800 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.970892e-08,
     'losses/train_center_loss': 0.56319726,
     'losses/train_regression_loss': 0.92253894,
     'losses/train_semantic_loss': 2.0084302,
     'losses/train_total_loss': 3.4941664}
W0104 21:38:16.254729 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 90800, expected updated value to be 90900, but it was 91000.
I0104 21:38:16.255559 139897736877696 controller.py:457] train | step:  91000 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.8931137e-08,
     'losses/train_center_loss': 0.5780135,
     'losses/train_regression_loss': 0.92251813,
     'losses/train_semantic_loss': 2.0044062,
     'losses/train_total_loss': 3.5049376}
I0104 21:38:23.840105 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-91000.
W0104 21:49:23.824297 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 91000, expected updated value to be 91100, but it was 91200.
I0104 21:49:23.825115 139897736877696 controller.py:457] train | step:  91200 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.815165e-08,
     'losses/train_center_loss': 0.55262977,
     'losses/train_regression_loss': 0.9180774,
     'losses/train_semantic_loss': 1.9945428,
     'losses/train_total_loss': 3.4652495}
W0104 22:00:21.867140 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 91200, expected updated value to be 91300, but it was 91400.
I0104 22:00:21.867949 139897736877696 controller.py:457] train | step:  91400 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.7370395e-08,
     'losses/train_center_loss': 0.54632777,
     'losses/train_regression_loss': 0.9249703,
     'losses/train_semantic_loss': 2.0049982,
     'losses/train_total_loss': 3.4762964}
W0104 22:11:23.508622 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 91400, expected updated value to be 91500, but it was 91600.
I0104 22:11:23.509441 139897736877696 controller.py:457] train | step:  91600 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.6587288e-08,
     'losses/train_center_loss': 0.55572706,
     'losses/train_regression_loss': 0.9232614,
     'losses/train_semantic_loss': 1.9891046,
     'losses/train_total_loss': 3.4680927}
W0104 22:22:25.281872 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 91600, expected updated value to be 91700, but it was 91800.
I0104 22:22:25.282693 139897736877696 controller.py:457] train | step:  91800 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.5802348e-08,
     'losses/train_center_loss': 0.55161667,
     'losses/train_regression_loss': 0.9201346,
     'losses/train_semantic_loss': 1.9997017,
     'losses/train_total_loss': 3.4714527}
W0104 22:33:28.274628 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 91800, expected updated value to be 91900, but it was 92000.
I0104 22:33:28.275435 139897736877696 controller.py:457] train | step:  92000 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.501546e-08,
     'losses/train_center_loss': 0.5453266,
     'losses/train_regression_loss': 0.9215753,
     'losses/train_semantic_loss': 1.9988312,
     'losses/train_total_loss': 3.465733}
I0104 22:33:35.674068 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-92000.
W0104 22:44:36.554920 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 92000, expected updated value to be 92100, but it was 92200.
I0104 22:44:36.555862 139897736877696 controller.py:457] train | step:  92200 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.4226627e-08,
     'losses/train_center_loss': 0.57169497,
     'losses/train_regression_loss': 0.9223454,
     'losses/train_semantic_loss': 2.037612,
     'losses/train_total_loss': 3.5316532}
W0104 22:55:35.658116 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 92200, expected updated value to be 92300, but it was 92400.
I0104 22:55:35.658926 139897736877696 controller.py:457] train | step:  92400 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.3435747e-08,
     'losses/train_center_loss': 0.5640148,
     'losses/train_regression_loss': 0.9158407,
     'losses/train_semantic_loss': 1.9999477,
     'losses/train_total_loss': 3.4798021}
W0104 23:06:32.275723 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 92400, expected updated value to be 92500, but it was 92600.
I0104 23:06:32.276529 139897736877696 controller.py:457] train | step:  92600 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.264281e-08,
     'losses/train_center_loss': 0.5512167,
     'losses/train_regression_loss': 0.92120546,
     'losses/train_semantic_loss': 2.009941,
     'losses/train_total_loss': 3.4823623}
W0104 23:17:32.237977 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 92600, expected updated value to be 92700, but it was 92800.
I0104 23:17:32.238779 139897736877696 controller.py:457] train | step:  92800 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.184772e-08,
     'losses/train_center_loss': 0.56819534,
     'losses/train_regression_loss': 0.9250283,
     'losses/train_semantic_loss': 1.9886099,
     'losses/train_total_loss': 3.4818335}
W0104 23:28:33.582249 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 92800, expected updated value to be 92900, but it was 93000.
I0104 23:28:33.583058 139897736877696 controller.py:457] train | step:  93000 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.105039e-08,
     'losses/train_center_loss': 0.55098796,
     'losses/train_regression_loss': 0.9210357,
     'losses/train_semantic_loss': 1.9773968,
     'losses/train_total_loss': 3.4494202}
I0104 23:28:40.999784 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-93000.
W0104 23:39:43.741340 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 93000, expected updated value to be 93100, but it was 93200.
I0104 23:39:43.742151 139897736877696 controller.py:457] train | step:  93200 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.0250813e-08,
     'losses/train_center_loss': 0.55092424,
     'losses/train_regression_loss': 0.9298172,
     'losses/train_semantic_loss': 1.9844974,
     'losses/train_total_loss': 3.4652383}
W0104 23:50:41.644733 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 93200, expected updated value to be 93300, but it was 93400.
I0104 23:50:41.645545 139897736877696 controller.py:457] train | step:  93400 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.9448858e-08,
     'losses/train_center_loss': 0.559328,
     'losses/train_regression_loss': 0.92162925,
     'losses/train_semantic_loss': 2.0151076,
     'losses/train_total_loss': 3.4960651}
W0105 00:01:45.488542 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 93400, expected updated value to be 93500, but it was 93600.
I0105 00:01:45.489372 139897736877696 controller.py:457] train | step:  93600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.8644482e-08,
     'losses/train_center_loss': 0.558463,
     'losses/train_regression_loss': 0.9304145,
     'losses/train_semantic_loss': 1.9995031,
     'losses/train_total_loss': 3.4883804}
W0105 00:12:46.365778 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 93600, expected updated value to be 93700, but it was 93800.
I0105 00:12:46.379804 139897736877696 controller.py:457] train | step:  93800 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.7837576e-08,
     'losses/train_center_loss': 0.56355774,
     'losses/train_regression_loss': 0.9224134,
     'losses/train_semantic_loss': 2.0088232,
     'losses/train_total_loss': 3.4947944}
W0105 00:23:47.453599 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 93800, expected updated value to be 93900, but it was 94000.
I0105 00:23:47.454412 139897736877696 controller.py:457] train | step:  94000 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.7028078e-08,
     'losses/train_center_loss': 0.5751649,
     'losses/train_regression_loss': 0.9255588,
     'losses/train_semantic_loss': 1.9865478,
     'losses/train_total_loss': 3.4872718}
I0105 00:23:55.434190 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-94000.
W0105 00:34:52.406732 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 94000, expected updated value to be 94100, but it was 94200.
I0105 00:34:52.407559 139897736877696 controller.py:457] train | step:  94200 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.6215876e-08,
     'losses/train_center_loss': 0.5536483,
     'losses/train_regression_loss': 0.91739625,
     'losses/train_semantic_loss': 1.9641333,
     'losses/train_total_loss': 3.4351773}
W0105 00:45:54.570668 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 94200, expected updated value to be 94300, but it was 94400.
I0105 00:45:54.571471 139897736877696 controller.py:457] train | step:  94400 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.5400842e-08,
     'losses/train_center_loss': 0.5449699,
     'losses/train_regression_loss': 0.9160443,
     'losses/train_semantic_loss': 1.9921948,
     'losses/train_total_loss': 3.4532092}
W0105 00:56:54.865771 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 94400, expected updated value to be 94500, but it was 94600.
I0105 00:56:54.866571 139897736877696 controller.py:457] train | step:  94600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.4582924e-08,
     'losses/train_center_loss': 0.5711649,
     'losses/train_regression_loss': 0.9210706,
     'losses/train_semantic_loss': 2.02023,
     'losses/train_total_loss': 3.5124662}
W0105 01:07:57.354753 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 94600, expected updated value to be 94700, but it was 94800.
I0105 01:07:57.355599 139897736877696 controller.py:457] train | step:  94800 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.376194e-08,
     'losses/train_center_loss': 0.56238824,
     'losses/train_regression_loss': 0.9221483,
     'losses/train_semantic_loss': 2.0022209,
     'losses/train_total_loss': 3.4867578}
W0105 01:18:56.187692 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 94800, expected updated value to be 94900, but it was 95000.
I0105 01:18:56.188665 139897736877696 controller.py:457] train | step:  95000 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.293782e-08,
     'losses/train_center_loss': 0.5693325,
     'losses/train_regression_loss': 0.9193375,
     'losses/train_semantic_loss': 1.9831809,
     'losses/train_total_loss': 3.47185}
I0105 01:19:07.231709 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-95000.
W0105 01:30:04.798480 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 95000, expected updated value to be 95100, but it was 95200.
I0105 01:30:04.799309 139897736877696 controller.py:457] train | step:  95200 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.2110362e-08,
     'losses/train_center_loss': 0.56449836,
     'losses/train_regression_loss': 0.92607725,
     'losses/train_semantic_loss': 2.0273263,
     'losses/train_total_loss': 3.5179017}
W0105 01:41:04.400070 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 95200, expected updated value to be 95300, but it was 95400.
I0105 01:41:04.400901 139897736877696 controller.py:457] train | step:  95400 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.1279483e-08,
     'losses/train_center_loss': 0.5558895,
     'losses/train_regression_loss': 0.917666,
     'losses/train_semantic_loss': 2.001988,
     'losses/train_total_loss': 3.4755437}
W0105 01:52:03.909084 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 95400, expected updated value to be 95500, but it was 95600.
I0105 01:52:03.909886 139897736877696 controller.py:457] train | step:  95600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.0444979e-08,
     'losses/train_center_loss': 0.562661,
     'losses/train_regression_loss': 0.9253395,
     'losses/train_semantic_loss': 2.0017915,
     'losses/train_total_loss': 3.4897926}
W0105 02:02:59.923379 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 95600, expected updated value to be 95700, but it was 95800.
I0105 02:02:59.924186 139897736877696 controller.py:457] train | step:  95800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.9606643e-08,
     'losses/train_center_loss': 0.54417574,
     'losses/train_regression_loss': 0.91279703,
     'losses/train_semantic_loss': 1.994216,
     'losses/train_total_loss': 3.4511886}
W0105 02:14:01.602078 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 95800, expected updated value to be 95900, but it was 96000.
I0105 02:14:01.602932 139897736877696 controller.py:457] train | step:  96000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.8764332e-08,
     'losses/train_center_loss': 0.55005133,
     'losses/train_regression_loss': 0.91452426,
     'losses/train_semantic_loss': 1.996435,
     'losses/train_total_loss': 3.4610102}
I0105 02:14:08.998733 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-96000.
W0105 02:25:09.198290 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 96000, expected updated value to be 96100, but it was 96200.
I0105 02:25:09.199268 139897736877696 controller.py:457] train | step:  96200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.7917774e-08,
     'losses/train_center_loss': 0.5619677,
     'losses/train_regression_loss': 0.9209286,
     'losses/train_semantic_loss': 2.010736,
     'losses/train_total_loss': 3.4936316}
W0105 02:36:11.823054 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 96200, expected updated value to be 96300, but it was 96400.
I0105 02:36:11.823862 139897736877696 controller.py:457] train | step:  96400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.7066771e-08,
     'losses/train_center_loss': 0.5510371,
     'losses/train_regression_loss': 0.9139012,
     'losses/train_semantic_loss': 1.9916977,
     'losses/train_total_loss': 3.4566357}
W0105 02:47:11.558972 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 96400, expected updated value to be 96500, but it was 96600.
I0105 02:47:11.559784 139897736877696 controller.py:457] train | step:  96600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.6210999e-08,
     'losses/train_center_loss': 0.5513932,
     'losses/train_regression_loss': 0.91562116,
     'losses/train_semantic_loss': 1.9908627,
     'losses/train_total_loss': 3.4578767}
W0105 02:58:09.023451 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 96600, expected updated value to be 96700, but it was 96800.
I0105 02:58:09.048044 139897736877696 controller.py:457] train | step:  96800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.53502e-08,
     'losses/train_center_loss': 0.5604797,
     'losses/train_regression_loss': 0.92227507,
     'losses/train_semantic_loss': 2.0141985,
     'losses/train_total_loss': 3.496953}
W0105 03:09:11.556949 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 96800, expected updated value to be 96900, but it was 97000.
I0105 03:09:11.557795 139897736877696 controller.py:457] train | step:  97000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.4483972e-08,
     'losses/train_center_loss': 0.55211025,
     'losses/train_regression_loss': 0.9160482,
     'losses/train_semantic_loss': 1.9719464,
     'losses/train_total_loss': 3.440105}
I0105 03:09:19.314733 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-97000.
W0105 03:20:18.765923 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 97000, expected updated value to be 97100, but it was 97200.
I0105 03:20:18.766714 139897736877696 controller.py:457] train | step:  97200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.36119755e-08,
     'losses/train_center_loss': 0.55628085,
     'losses/train_regression_loss': 0.91955626,
     'losses/train_semantic_loss': 2.0087774,
     'losses/train_total_loss': 3.4846148}
W0105 03:31:18.781751 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 97200, expected updated value to be 97300, but it was 97400.
I0105 03:31:18.782571 139897736877696 controller.py:457] train | step:  97400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.273372e-08,
     'losses/train_center_loss': 0.57181406,
     'losses/train_regression_loss': 0.92237455,
     'losses/train_semantic_loss': 1.9746065,
     'losses/train_total_loss': 3.468795}
W0105 03:42:21.570285 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 97400, expected updated value to be 97500, but it was 97600.
I0105 03:42:21.571093 139897736877696 controller.py:457] train | step:  97600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.184865e-08,
     'losses/train_center_loss': 0.5463634,
     'losses/train_regression_loss': 0.91597056,
     'losses/train_semantic_loss': 2.0031111,
     'losses/train_total_loss': 3.4654455}
W0105 03:53:24.056366 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 97600, expected updated value to be 97700, but it was 97800.
I0105 03:53:24.057298 139897736877696 controller.py:457] train | step:  97800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.0956194e-08,
     'losses/train_center_loss': 0.55145,
     'losses/train_regression_loss': 0.9177688,
     'losses/train_semantic_loss': 2.0016122,
     'losses/train_total_loss': 3.4708314}
W0105 04:04:23.449359 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 97800, expected updated value to be 97900, but it was 98000.
I0105 04:04:23.450157 139897736877696 controller.py:457] train | step:  98000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.0055545e-08,
     'losses/train_center_loss': 0.54712373,
     'losses/train_regression_loss': 0.91681516,
     'losses/train_semantic_loss': 2.0115354,
     'losses/train_total_loss': 3.4754744}
I0105 04:04:31.095016 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-98000.
W0105 04:15:31.479311 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 98000, expected updated value to be 98100, but it was 98200.
I0105 04:15:31.480139 139897736877696 controller.py:457] train | step:  98200 | steps/sec:    0.3 | output: 
    {'learning_rate': 9.1458565e-09,
     'losses/train_center_loss': 0.5607309,
     'losses/train_regression_loss': 0.9197766,
     'losses/train_semantic_loss': 1.9900038,
     'losses/train_total_loss': 3.470511}
W0105 04:26:30.601929 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 98200, expected updated value to be 98300, but it was 98400.
I0105 04:26:30.602727 139897736877696 controller.py:457] train | step:  98400 | steps/sec:    0.3 | output: 
    {'learning_rate': 8.225953e-09,
     'losses/train_center_loss': 0.540283,
     'losses/train_regression_loss': 0.91717744,
     'losses/train_semantic_loss': 2.0218463,
     'losses/train_total_loss': 3.4793062}
W0105 04:37:29.901376 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 98400, expected updated value to be 98500, but it was 98600.
I0105 04:37:29.902170 139897736877696 controller.py:457] train | step:  98600 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.294477e-09,
     'losses/train_center_loss': 0.56242025,
     'losses/train_regression_loss': 0.92340225,
     'losses/train_semantic_loss': 1.9755505,
     'losses/train_total_loss': 3.4613738}
W0105 04:48:32.131191 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 98600, expected updated value to be 98700, but it was 98800.
I0105 04:48:32.132006 139897736877696 controller.py:457] train | step:  98800 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.349549e-09,
     'losses/train_center_loss': 0.5579712,
     'losses/train_regression_loss': 0.9233548,
     'losses/train_semantic_loss': 1.994422,
     'losses/train_total_loss': 3.4757483}
W0105 04:59:28.863583 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 98800, expected updated value to be 98900, but it was 99000.
I0105 04:59:28.864411 139897736877696 controller.py:457] train | step:  99000 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.388632e-09,
     'losses/train_center_loss': 0.55440027,
     'losses/train_regression_loss': 0.91784865,
     'losses/train_semantic_loss': 1.9920588,
     'losses/train_total_loss': 3.4643073}
I0105 04:59:36.635138 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-99000.
W0105 05:10:39.916848 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 99000, expected updated value to be 99100, but it was 99200.
I0105 05:10:39.917789 139897736877696 controller.py:457] train | step:  99200 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.408194e-09,
     'losses/train_center_loss': 0.55436087,
     'losses/train_regression_loss': 0.92557114,
     'losses/train_semantic_loss': 2.0012875,
     'losses/train_total_loss': 3.48122}
W0105 05:21:39.346729 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 99200, expected updated value to be 99300, but it was 99400.
I0105 05:21:39.347534 139897736877696 controller.py:457] train | step:  99400 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.4026237e-09,
     'losses/train_center_loss': 0.5690926,
     'losses/train_regression_loss': 0.92417026,
     'losses/train_semantic_loss': 2.0104783,
     'losses/train_total_loss': 3.5037408}
W0105 05:32:41.436541 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 99400, expected updated value to be 99500, but it was 99600.
I0105 05:32:41.437340 139897736877696 controller.py:457] train | step:  99600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.3622932e-09,
     'losses/train_center_loss': 0.5498983,
     'losses/train_regression_loss': 0.9252628,
     'losses/train_semantic_loss': 1.9879258,
     'losses/train_total_loss': 3.463087}
W0105 05:43:37.790662 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 99600, expected updated value to be 99700, but it was 99800.
I0105 05:43:37.791460 139897736877696 controller.py:457] train | step:  99800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.2659044e-09,
     'losses/train_center_loss': 0.54127306,
     'losses/train_regression_loss': 0.91506577,
     'losses/train_semantic_loss': 1.9798174,
     'losses/train_total_loss': 3.4361558}
W0105 05:54:39.344648 139897736877696 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 99800, expected updated value to be 99900, but it was 100000.
I0105 05:54:39.345483 139897736877696 controller.py:457] train | step:  100000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0,
     'losses/train_center_loss': 0.53828186,
     'losses/train_regression_loss': 0.91491944,
     'losses/train_semantic_loss': 2.0014331,
     'losses/train_total_loss': 3.4546344}
I0105 05:54:46.744225 139897736877696 controller.py:486] saved checkpoint to ../model_dir/deepyeast_001/ckpt-100000.
