2022-12-25 10:09:12.056347: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-25 10:09:12.773884: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-12-25 10:09:26.392088: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib64:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/mpfr-4.1.0-4owr5jskgrebkppacvwkfa7tdtlqjalg/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/gmp-6.2.1-rg3gv5myy7lt46cjxvmdmsghhyhxguqo/lib:/work/FAC/FBM/DMF/smartin/cellfusion/wanlan/miniconda3/envs/tf210/lib/
2022-12-25 10:09:26.392227: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib64:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/mpfr-4.1.0-4owr5jskgrebkppacvwkfa7tdtlqjalg/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/gmp-6.2.1-rg3gv5myy7lt46cjxvmdmsghhyhxguqo/lib:/work/FAC/FBM/DMF/smartin/cellfusion/wanlan/miniconda3/envs/tf210/lib/
2022-12-25 10:09:26.392238: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-12-25 10:09:46.971931: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-25 10:09:47.988764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38224 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:21:00.0, compute capability: 8.0
2022-12-25 10:09:47.990824: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 38224 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:e2:00.0, compute capability: 8.0
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I1225 10:09:48.361596 140207281448576 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I1225 10:09:48.369246 140207281448576 deeplab.py:58] Synchronized Batchnorm is used.
I1225 10:09:48.369971 140207281448576 axial_resnet_instances.py:144] Axial-ResNet final config: {'num_blocks': [3, 6, 3, 3], 'backbone_layer_multiplier': 4.5, 'width_multiplier': 1, 'stem_width_multiplier': 1, 'output_stride': 16, 'classification_mode': True, 'backbone_type': 'wider_resnet', 'use_axial_beyond_stride': 16, 'backbone_use_transformer_beyond_stride': 0, 'extra_decoder_use_transformer_beyond_stride': 32, 'backbone_decoder_num_stacks': 0, 'backbone_decoder_blocks_per_stage': 1, 'extra_decoder_num_stacks': 0, 'extra_decoder_blocks_per_stage': 1, 'max_num_mask_slots': 128, 'num_mask_slots': 128, 'memory_channels': 256, 'base_transformer_expansion': 1.0, 'global_feed_forward_network_channels': 256, 'high_resolution_output_stride': 4, 'activation': 'relu', 'block_group_config': {'attention_bottleneck_expansion': 4, 'drop_path_keep_prob': 0.8, 'drop_path_beyond_stride': 4, 'drop_path_schedule': 'linear', 'positional_encoding_type': None, 'use_global_beyond_stride': 0, 'use_sac_beyond_stride': 0, 'use_squeeze_and_excite': False, 'conv_use_recompute_grad': True, 'axial_use_recompute_grad': True, 'recompute_within_stride': 0, 'transformer_use_recompute_grad': False, 'axial_layer_config': {'query_shape': (129, 129), 'key_expansion': 2, 'value_expansion': 4, 'memory_flange': (32, 32), 'double_global_attention': False, 'num_heads': 8, 'use_query_rpe_similarity': True, 'use_key_rpe_similarity': True, 'use_content_similarity': True, 'retrieve_value_rpe': True, 'retrieve_value_content': True, 'initialization_std_for_query_key_rpe': 1.0, 'initialization_std_for_value_rpe': 1.0, 'self_attention_activation': 'softmax'}, 'dual_path_transformer_layer_config': {'num_heads': 8, 'bottleneck_expansion': 2, 'key_expansion': 1, 'value_expansion': 2, 'feed_forward_network_channels': 2048, 'use_memory_self_attention': True, 'use_pixel2memory_feedback_attention': True, 'transformer_activation': 'softmax'}}, 'bn_layer': functools.partial(<class 'keras.layers.normalization.batch_normalization.SyncBatchNormalization'>, momentum=0.99, epsilon=0.001), 'conv_kernel_weight_decay': 0.0}
I1225 10:09:48.827773 140207281448576 deeplab.py:99] Setting pooling size to (33, 33)
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.116241 140207281448576 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.119051 140207281448576 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.120962 140207281448576 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.121575 140207281448576 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.123943 140207281448576 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.124497 140207281448576 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.126023 140207281448576 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.126574 140207281448576 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.128867 140207281448576 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.129410 140207281448576 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1225 10:09:53.139051 140207281448576 controller.py:391] restoring or initializing model...
I1225 10:09:53.334794 140207281448576 controller.py:395] restored model from ../model_dir/ckpt-20000.
I1225 10:09:53.334950 140207281448576 controller.py:217] restored from checkpoint: ../model_dir/ckpt-20000
I1225 10:09:53.335163 140207281448576 controller.py:236] train | step:  20000 | training until step 40000...
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1225 10:09:54.960790 140207281448576 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1225 10:09:55.004394 140207281448576 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1225 10:09:55.018721 140207281448576 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1225 10:09:56.141072 140207281448576 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1225 10:09:56.156211 140207281448576 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1225 10:09:56.170895 140207281448576 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1225 10:09:56.370840 140207281448576 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1225 10:09:56.385781 140207281448576 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1225 10:09:56.400266 140207281448576 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1225 10:09:56.504328 140207281448576 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
2022-12-25 10:20:09.791702: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8401
2022-12-25 10:20:10.060967: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8401
2022-12-25 10:20:19.179520: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-12-25 10:20:20.563840: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
W1225 10:33:28.898377 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 20000, expected updated value to be 20100, but it was 20200.
I1225 10:33:28.920880 140207281448576 controller.py:457] train | step:  20200 | steps/sec:    0.1 | output: 
    {'learning_rate': 0.00039829602,
     'losses/train_center_loss': 0.13970914,
     'losses/train_regression_loss': 1.392257,
     'losses/train_semantic_loss': 2.0782654,
     'losses/train_total_loss': 3.6102326}
W1225 10:46:18.725936 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 20200, expected updated value to be 20300, but it was 20400.
I1225 10:46:18.726975 140207281448576 controller.py:457] train | step:  20400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0003946733,
     'losses/train_center_loss': 0.15157616,
     'losses/train_regression_loss': 1.4514456,
     'losses/train_semantic_loss': 2.154684,
     'losses/train_total_loss': 3.7577057}
W1225 10:59:02.789956 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 20400, expected updated value to be 20500, but it was 20600.
I1225 10:59:02.791029 140207281448576 controller.py:457] train | step:  20600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0003910469,
     'losses/train_center_loss': 0.14088137,
     'losses/train_regression_loss': 1.4016882,
     'losses/train_semantic_loss': 2.0913591,
     'losses/train_total_loss': 3.6339295}
W1225 11:11:49.420275 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 20600, expected updated value to be 20700, but it was 20800.
I1225 11:11:49.421307 140207281448576 controller.py:457] train | step:  20800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00038741675,
     'losses/train_center_loss': 0.15307847,
     'losses/train_regression_loss': 1.4127346,
     'losses/train_semantic_loss': 2.0665634,
     'losses/train_total_loss': 3.6323774}
W1225 11:24:37.315912 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 20800, expected updated value to be 20900, but it was 21000.
I1225 11:24:37.316934 140207281448576 controller.py:457] train | step:  21000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0003837828,
     'losses/train_center_loss': 0.15087596,
     'losses/train_regression_loss': 1.3993825,
     'losses/train_semantic_loss': 2.0881522,
     'losses/train_total_loss': 3.6384106}
I1225 11:24:46.261424 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-21000.
W1225 11:37:40.467408 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 21000, expected updated value to be 21100, but it was 21200.
I1225 11:37:40.468425 140207281448576 controller.py:457] train | step:  21200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00038014507,
     'losses/train_center_loss': 0.41243592,
     'losses/train_regression_loss': 2.2566977,
     'losses/train_semantic_loss': 3.4778054,
     'losses/train_total_loss': 6.1469393}
W1225 11:50:28.692502 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 21200, expected updated value to be 21300, but it was 21400.
I1225 11:50:28.693340 140207281448576 controller.py:457] train | step:  21400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00037650342,
     'losses/train_center_loss': 0.2451836,
     'losses/train_regression_loss': 1.718991,
     'losses/train_semantic_loss': 2.667337,
     'losses/train_total_loss': 4.6315117}
W1225 12:03:20.347833 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 21400, expected updated value to be 21500, but it was 21600.
I1225 12:03:20.348702 140207281448576 controller.py:457] train | step:  21600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00037285784,
     'losses/train_center_loss': 0.17177166,
     'losses/train_regression_loss': 1.4991813,
     'losses/train_semantic_loss': 2.341018,
     'losses/train_total_loss': 4.0119715}
W1225 12:16:06.614882 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 21600, expected updated value to be 21700, but it was 21800.
I1225 12:16:06.615884 140207281448576 controller.py:457] train | step:  21800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00036920834,
     'losses/train_center_loss': 0.17898224,
     'losses/train_regression_loss': 1.5675495,
     'losses/train_semantic_loss': 2.3603141,
     'losses/train_total_loss': 4.106846}
W1225 12:28:49.375044 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 21800, expected updated value to be 21900, but it was 22000.
I1225 12:28:49.375912 140207281448576 controller.py:457] train | step:  22000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0003655548,
     'losses/train_center_loss': 0.15307456,
     'losses/train_regression_loss': 1.4339812,
     'losses/train_semantic_loss': 2.154311,
     'losses/train_total_loss': 3.741367}
I1225 12:28:58.077081 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-22000.
W1225 12:41:51.345119 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 22000, expected updated value to be 22100, but it was 22200.
I1225 12:41:51.346163 140207281448576 controller.py:457] train | step:  22200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00036189726,
     'losses/train_center_loss': 0.14568701,
     'losses/train_regression_loss': 1.4126081,
     'losses/train_semantic_loss': 2.115713,
     'losses/train_total_loss': 3.6740072}
W1225 12:54:36.088804 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 22200, expected updated value to be 22300, but it was 22400.
I1225 12:54:36.089675 140207281448576 controller.py:457] train | step:  22400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00035823556,
     'losses/train_center_loss': 0.15326835,
     'losses/train_regression_loss': 1.4039847,
     'losses/train_semantic_loss': 2.1092718,
     'losses/train_total_loss': 3.6665254}
W1225 13:07:14.808610 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 22400, expected updated value to be 22500, but it was 22600.
I1225 13:07:14.809490 140207281448576 controller.py:457] train | step:  22600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0003545697,
     'losses/train_center_loss': 0.14627261,
     'losses/train_regression_loss': 1.4317772,
     'losses/train_semantic_loss': 2.1168923,
     'losses/train_total_loss': 3.694942}
W1225 13:19:59.418211 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 22600, expected updated value to be 22700, but it was 22800.
I1225 13:19:59.419057 140207281448576 controller.py:457] train | step:  22800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0003508996,
     'losses/train_center_loss': 0.14302713,
     'losses/train_regression_loss': 1.4167961,
     'losses/train_semantic_loss': 2.1442556,
     'losses/train_total_loss': 3.704079}
W1225 13:32:44.813074 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 22800, expected updated value to be 22900, but it was 23000.
I1225 13:32:44.814097 140207281448576 controller.py:457] train | step:  23000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00034722526,
     'losses/train_center_loss': 0.14634001,
     'losses/train_regression_loss': 1.3919652,
     'losses/train_semantic_loss': 2.1328068,
     'losses/train_total_loss': 3.671112}
I1225 13:32:52.680256 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-23000.
W1225 13:45:37.509156 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 23000, expected updated value to be 23100, but it was 23200.
I1225 13:45:37.527824 140207281448576 controller.py:457] train | step:  23200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0003435466,
     'losses/train_center_loss': 0.13478586,
     'losses/train_regression_loss': 1.3514551,
     'losses/train_semantic_loss': 2.0223665,
     'losses/train_total_loss': 3.5086071}
W1225 13:58:18.690326 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 23200, expected updated value to be 23300, but it was 23400.
I1225 13:58:18.691177 140207281448576 controller.py:457] train | step:  23400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00033986356,
     'losses/train_center_loss': 0.13685548,
     'losses/train_regression_loss': 1.3564106,
     'losses/train_semantic_loss': 2.0530632,
     'losses/train_total_loss': 3.546329}
W1225 14:10:58.783749 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 23400, expected updated value to be 23500, but it was 23600.
I1225 14:10:58.784603 140207281448576 controller.py:457] train | step:  23600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00033617605,
     'losses/train_center_loss': 0.12550972,
     'losses/train_regression_loss': 1.3335081,
     'losses/train_semantic_loss': 1.9979862,
     'losses/train_total_loss': 3.4570048}
W1225 14:23:47.018616 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 23600, expected updated value to be 23700, but it was 23800.
I1225 14:23:47.019461 140207281448576 controller.py:457] train | step:  23800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00033248402,
     'losses/train_center_loss': 0.12937813,
     'losses/train_regression_loss': 1.3098831,
     'losses/train_semantic_loss': 1.9745691,
     'losses/train_total_loss': 3.4138303}
W1225 14:36:30.945800 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 23800, expected updated value to be 23900, but it was 24000.
I1225 14:36:30.946748 140207281448576 controller.py:457] train | step:  24000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00032878746,
     'losses/train_center_loss': 0.13256274,
     'losses/train_regression_loss': 1.3443811,
     'losses/train_semantic_loss': 2.0392685,
     'losses/train_total_loss': 3.5162117}
I1225 14:36:39.860242 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-24000.
W1225 14:49:22.321823 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 24000, expected updated value to be 24100, but it was 24200.
I1225 14:49:22.322710 140207281448576 controller.py:457] train | step:  24200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00032508626,
     'losses/train_center_loss': 0.1238337,
     'losses/train_regression_loss': 1.3180944,
     'losses/train_semantic_loss': 1.9819264,
     'losses/train_total_loss': 3.4238544}
W1225 15:02:07.805237 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 24200, expected updated value to be 24300, but it was 24400.
I1225 15:02:07.806078 140207281448576 controller.py:457] train | step:  24400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00032138042,
     'losses/train_center_loss': 0.12141581,
     'losses/train_regression_loss': 1.3349911,
     'losses/train_semantic_loss': 2.0201583,
     'losses/train_total_loss': 3.4765644}
W1225 15:14:52.470166 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 24400, expected updated value to be 24500, but it was 24600.
I1225 15:14:52.471004 140207281448576 controller.py:457] train | step:  24600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0003176698,
     'losses/train_center_loss': 0.12509498,
     'losses/train_regression_loss': 1.3410461,
     'losses/train_semantic_loss': 1.9805589,
     'losses/train_total_loss': 3.4467}
W1225 15:27:33.913628 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 24600, expected updated value to be 24700, but it was 24800.
I1225 15:27:33.932971 140207281448576 controller.py:457] train | step:  24800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00031395437,
     'losses/train_center_loss': 0.1213654,
     'losses/train_regression_loss': 1.3085055,
     'losses/train_semantic_loss': 1.9914263,
     'losses/train_total_loss': 3.4212983}
W1225 15:40:18.529825 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 24800, expected updated value to be 24900, but it was 25000.
I1225 15:40:18.530693 140207281448576 controller.py:457] train | step:  25000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.000310234,
     'losses/train_center_loss': 0.11625578,
     'losses/train_regression_loss': 1.2942581,
     'losses/train_semantic_loss': 1.9370527,
     'losses/train_total_loss': 3.347567}
I1225 15:40:26.650297 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-25000.
W1225 15:53:20.575611 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 25000, expected updated value to be 25100, but it was 25200.
I1225 15:53:20.576510 140207281448576 controller.py:457] train | step:  25200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0003065087,
     'losses/train_center_loss': 0.12111053,
     'losses/train_regression_loss': 1.3153876,
     'losses/train_semantic_loss': 1.9621315,
     'losses/train_total_loss': 3.3986292}
W1225 16:06:02.765523 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 25200, expected updated value to be 25300, but it was 25400.
I1225 16:06:02.766518 140207281448576 controller.py:457] train | step:  25400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00030277838,
     'losses/train_center_loss': 0.12548408,
     'losses/train_regression_loss': 1.3101776,
     'losses/train_semantic_loss': 1.9865779,
     'losses/train_total_loss': 3.4222405}
W1225 16:18:45.179574 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 25400, expected updated value to be 25500, but it was 25600.
I1225 16:18:45.180847 140207281448576 controller.py:457] train | step:  25600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00029904293,
     'losses/train_center_loss': 0.17376526,
     'losses/train_regression_loss': 1.3171791,
     'losses/train_semantic_loss': 1.9723845,
     'losses/train_total_loss': 3.4633284}
W1225 16:31:31.060961 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 25600, expected updated value to be 25700, but it was 25800.
I1225 16:31:31.061811 140207281448576 controller.py:457] train | step:  25800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00029530228,
     'losses/train_center_loss': 0.121398784,
     'losses/train_regression_loss': 1.2878042,
     'losses/train_semantic_loss': 1.9400573,
     'losses/train_total_loss': 3.3492603}
W1225 16:44:18.494293 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 25800, expected updated value to be 25900, but it was 26000.
I1225 16:44:18.495125 140207281448576 controller.py:457] train | step:  26000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00029155638,
     'losses/train_center_loss': 0.12092926,
     'losses/train_regression_loss': 1.2910571,
     'losses/train_semantic_loss': 1.9255568,
     'losses/train_total_loss': 3.3375432}
I1225 16:44:26.314576 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-26000.
W1225 16:57:15.225118 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 26000, expected updated value to be 26100, but it was 26200.
I1225 16:57:15.225963 140207281448576 controller.py:457] train | step:  26200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0002878051,
     'losses/train_center_loss': 0.11625849,
     'losses/train_regression_loss': 1.2686486,
     'losses/train_semantic_loss': 1.9140762,
     'losses/train_total_loss': 3.2989826}
W1225 17:09:54.933034 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 26200, expected updated value to be 26300, but it was 26400.
I1225 17:09:54.933926 140207281448576 controller.py:457] train | step:  26400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00028404835,
     'losses/train_center_loss': 0.11127199,
     'losses/train_regression_loss': 1.2445184,
     'losses/train_semantic_loss': 1.9369262,
     'losses/train_total_loss': 3.2927167}
W1225 17:22:47.465568 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 26400, expected updated value to be 26500, but it was 26600.
I1225 17:22:47.466565 140207281448576 controller.py:457] train | step:  26600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0002802861,
     'losses/train_center_loss': 0.12773916,
     'losses/train_regression_loss': 1.3955789,
     'losses/train_semantic_loss': 2.0091212,
     'losses/train_total_loss': 3.532439}
W1225 17:35:34.084311 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 26600, expected updated value to be 26700, but it was 26800.
I1225 17:35:34.085144 140207281448576 controller.py:457] train | step:  26800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00027651826,
     'losses/train_center_loss': 0.12040526,
     'losses/train_regression_loss': 1.29224,
     'losses/train_semantic_loss': 1.9317173,
     'losses/train_total_loss': 3.3443623}
W1225 17:48:21.085627 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 26800, expected updated value to be 26900, but it was 27000.
I1225 17:48:21.086474 140207281448576 controller.py:457] train | step:  27000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00027274468,
     'losses/train_center_loss': 0.114164084,
     'losses/train_regression_loss': 1.273241,
     'losses/train_semantic_loss': 1.932071,
     'losses/train_total_loss': 3.3194752}
I1225 17:48:29.253776 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-27000.
W1225 18:01:17.249886 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 27000, expected updated value to be 27100, but it was 27200.
I1225 18:01:17.250756 140207281448576 controller.py:457] train | step:  27200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0002689653,
     'losses/train_center_loss': 0.11002573,
     'losses/train_regression_loss': 1.2453212,
     'losses/train_semantic_loss': 1.8970526,
     'losses/train_total_loss': 3.2524}
W1225 18:13:54.778128 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 27200, expected updated value to be 27300, but it was 27400.
I1225 18:13:54.778950 140207281448576 controller.py:457] train | step:  27400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00026518,
     'losses/train_center_loss': 0.11156561,
     'losses/train_regression_loss': 1.2487758,
     'losses/train_semantic_loss': 1.9000976,
     'losses/train_total_loss': 3.2604394}
W1225 18:26:35.995874 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 27400, expected updated value to be 27500, but it was 27600.
I1225 18:26:35.996712 140207281448576 controller.py:457] train | step:  27600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00026138866,
     'losses/train_center_loss': 0.10975919,
     'losses/train_regression_loss': 1.2503151,
     'losses/train_semantic_loss': 1.9146329,
     'losses/train_total_loss': 3.2747073}
W1225 18:39:15.531842 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 27600, expected updated value to be 27700, but it was 27800.
I1225 18:39:15.546191 140207281448576 controller.py:457] train | step:  27800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00025759125,
     'losses/train_center_loss': 0.114220545,
     'losses/train_regression_loss': 1.2827442,
     'losses/train_semantic_loss': 1.9232876,
     'losses/train_total_loss': 3.3202527}
W1225 18:51:57.003857 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 27800, expected updated value to be 27900, but it was 28000.
I1225 18:51:57.004704 140207281448576 controller.py:457] train | step:  28000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0002537876,
     'losses/train_center_loss': 0.10698526,
     'losses/train_regression_loss': 1.2410206,
     'losses/train_semantic_loss': 1.9217246,
     'losses/train_total_loss': 3.2697306}
I1225 18:52:04.888485 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-28000.
W1225 19:04:46.619195 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 28000, expected updated value to be 28100, but it was 28200.
I1225 19:04:46.620068 140207281448576 controller.py:457] train | step:  28200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0002499776,
     'losses/train_center_loss': 0.10711415,
     'losses/train_regression_loss': 1.229181,
     'losses/train_semantic_loss': 1.8962063,
     'losses/train_total_loss': 3.2325017}
W1225 19:17:36.458280 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 28200, expected updated value to be 28300, but it was 28400.
I1225 19:17:36.459120 140207281448576 controller.py:457] train | step:  28400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00024616116,
     'losses/train_center_loss': 0.11392173,
     'losses/train_regression_loss': 1.262529,
     'losses/train_semantic_loss': 1.9201001,
     'losses/train_total_loss': 3.296551}
W1225 19:30:20.578510 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 28400, expected updated value to be 28500, but it was 28600.
I1225 19:30:20.579349 140207281448576 controller.py:457] train | step:  28600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0002423381,
     'losses/train_center_loss': 0.1132261,
     'losses/train_regression_loss': 1.2638599,
     'losses/train_semantic_loss': 2.0084252,
     'losses/train_total_loss': 3.3855104}
W1225 19:43:05.185987 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 28600, expected updated value to be 28700, but it was 28800.
I1225 19:43:05.186854 140207281448576 controller.py:457] train | step:  28800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00023850829,
     'losses/train_center_loss': 0.11478809,
     'losses/train_regression_loss': 1.2798237,
     'losses/train_semantic_loss': 1.8860446,
     'losses/train_total_loss': 3.2806568}
W1225 19:55:49.749515 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 28800, expected updated value to be 28900, but it was 29000.
I1225 19:55:49.750418 140207281448576 controller.py:457] train | step:  29000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00023467168,
     'losses/train_center_loss': 0.107853204,
     'losses/train_regression_loss': 1.2311716,
     'losses/train_semantic_loss': 1.8713372,
     'losses/train_total_loss': 3.210362}
I1225 19:55:57.232239 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-29000.
W1225 20:08:40.342157 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 29000, expected updated value to be 29100, but it was 29200.
I1225 20:08:40.343132 140207281448576 controller.py:457] train | step:  29200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00023082807,
     'losses/train_center_loss': 0.10320258,
     'losses/train_regression_loss': 1.2308011,
     'losses/train_semantic_loss': 1.8542871,
     'losses/train_total_loss': 3.188291}
W1225 20:21:33.103734 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 29200, expected updated value to be 29300, but it was 29400.
I1225 20:21:33.104592 140207281448576 controller.py:457] train | step:  29400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00022697734,
     'losses/train_center_loss': 0.10847965,
     'losses/train_regression_loss': 1.2376915,
     'losses/train_semantic_loss': 1.8698921,
     'losses/train_total_loss': 3.2160625}
W1225 20:34:13.264643 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 29400, expected updated value to be 29500, but it was 29600.
I1225 20:34:13.265507 140207281448576 controller.py:457] train | step:  29600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00022311936,
     'losses/train_center_loss': 0.10447709,
     'losses/train_regression_loss': 1.2065846,
     'losses/train_semantic_loss': 1.8711483,
     'losses/train_total_loss': 3.18221}
W1225 20:47:04.105378 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 29600, expected updated value to be 29700, but it was 29800.
I1225 20:47:04.106283 140207281448576 controller.py:457] train | step:  29800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00021925394,
     'losses/train_center_loss': 0.100448005,
     'losses/train_regression_loss': 1.2150673,
     'losses/train_semantic_loss': 1.8258185,
     'losses/train_total_loss': 3.1413336}
W1225 20:59:45.074746 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 29800, expected updated value to be 29900, but it was 30000.
I1225 20:59:45.075610 140207281448576 controller.py:457] train | step:  30000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00021538096,
     'losses/train_center_loss': 0.113875635,
     'losses/train_regression_loss': 1.243423,
     'losses/train_semantic_loss': 1.882005,
     'losses/train_total_loss': 3.2393034}
I1225 20:59:53.084814 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-30000.
W1225 21:12:35.895516 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 30000, expected updated value to be 30100, but it was 30200.
I1225 21:12:35.896389 140207281448576 controller.py:457] train | step:  30200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00021150021,
     'losses/train_center_loss': 0.104426615,
     'losses/train_regression_loss': 1.2236016,
     'losses/train_semantic_loss': 1.837626,
     'losses/train_total_loss': 3.165654}
W1225 21:25:20.435678 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 30200, expected updated value to be 30300, but it was 30400.
I1225 21:25:20.436539 140207281448576 controller.py:457] train | step:  30400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00020761152,
     'losses/train_center_loss': 0.10401555,
     'losses/train_regression_loss': 1.2467773,
     'losses/train_semantic_loss': 1.8961706,
     'losses/train_total_loss': 3.2469635}
W1225 21:38:05.773115 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 30400, expected updated value to be 30500, but it was 30600.
I1225 21:38:05.774004 140207281448576 controller.py:457] train | step:  30600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00020371472,
     'losses/train_center_loss': 0.10403452,
     'losses/train_regression_loss': 1.209988,
     'losses/train_semantic_loss': 1.8354318,
     'losses/train_total_loss': 3.1494536}
W1225 21:50:52.921219 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 30600, expected updated value to be 30700, but it was 30800.
I1225 21:50:52.922613 140207281448576 controller.py:457] train | step:  30800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0001998096,
     'losses/train_center_loss': 0.14564219,
     'losses/train_regression_loss': 1.3305545,
     'losses/train_semantic_loss': 2.2498,
     'losses/train_total_loss': 3.7259967}
W1225 22:03:42.755041 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 30800, expected updated value to be 30900, but it was 31000.
I1225 22:03:42.755864 140207281448576 controller.py:457] train | step:  31000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00019589603,
     'losses/train_center_loss': 0.14230008,
     'losses/train_regression_loss': 1.3015037,
     'losses/train_semantic_loss': 2.0573375,
     'losses/train_total_loss': 3.5011408}
I1225 22:03:50.808143 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-31000.
W1225 22:16:37.653320 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 31000, expected updated value to be 31100, but it was 31200.
I1225 22:16:37.654198 140207281448576 controller.py:457] train | step:  31200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00019197368,
     'losses/train_center_loss': 0.10992615,
     'losses/train_regression_loss': 1.2457993,
     'losses/train_semantic_loss': 1.9059067,
     'losses/train_total_loss': 3.2616308}
W1225 22:29:28.095623 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 31200, expected updated value to be 31300, but it was 31400.
I1225 22:29:28.096455 140207281448576 controller.py:457] train | step:  31400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00018804244,
     'losses/train_center_loss': 0.10425104,
     'losses/train_regression_loss': 1.2124709,
     'losses/train_semantic_loss': 1.8444357,
     'losses/train_total_loss': 3.1611586}
W1225 22:42:16.939453 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 31400, expected updated value to be 31500, but it was 31600.
I1225 22:42:16.940282 140207281448576 controller.py:457] train | step:  31600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00018410203,
     'losses/train_center_loss': 0.11769163,
     'losses/train_regression_loss': 1.2557383,
     'losses/train_semantic_loss': 1.971439,
     'losses/train_total_loss': 3.3448684}
W1225 22:55:07.319453 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 31600, expected updated value to be 31700, but it was 31800.
I1225 22:55:07.320317 140207281448576 controller.py:457] train | step:  31800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00018015227,
     'losses/train_center_loss': 0.11650755,
     'losses/train_regression_loss': 1.2705414,
     'losses/train_semantic_loss': 1.9948573,
     'losses/train_total_loss': 3.3819058}
W1225 23:07:50.124888 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 31800, expected updated value to be 31900, but it was 32000.
I1225 23:07:50.125789 140207281448576 controller.py:457] train | step:  32000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00017619283,
     'losses/train_center_loss': 0.10699169,
     'losses/train_regression_loss': 1.2465754,
     'losses/train_semantic_loss': 1.903655,
     'losses/train_total_loss': 3.2572222}
I1225 23:07:57.743161 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-32000.
W1225 23:20:43.041897 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 32000, expected updated value to be 32100, but it was 32200.
I1225 23:20:43.042897 140207281448576 controller.py:457] train | step:  32200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00017222349,
     'losses/train_center_loss': 0.1035224,
     'losses/train_regression_loss': 1.2009838,
     'losses/train_semantic_loss': 1.8720427,
     'losses/train_total_loss': 3.1765487}
W1225 23:33:21.614145 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 32200, expected updated value to be 32300, but it was 32400.
I1225 23:33:21.630173 140207281448576 controller.py:457] train | step:  32400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00016824395,
     'losses/train_center_loss': 0.109122925,
     'losses/train_regression_loss': 1.2381294,
     'losses/train_semantic_loss': 1.9586338,
     'losses/train_total_loss': 3.3058856}
W1225 23:46:11.176415 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 32400, expected updated value to be 32500, but it was 32600.
I1225 23:46:11.177278 140207281448576 controller.py:457] train | step:  32600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00016425394,
     'losses/train_center_loss': 0.09731871,
     'losses/train_regression_loss': 1.2001153,
     'losses/train_semantic_loss': 1.8312813,
     'losses/train_total_loss': 3.1287153}
W1225 23:58:55.685626 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 32600, expected updated value to be 32700, but it was 32800.
I1225 23:58:55.686491 140207281448576 controller.py:457] train | step:  32800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00016025316,
     'losses/train_center_loss': 0.099909745,
     'losses/train_regression_loss': 1.1961653,
     'losses/train_semantic_loss': 1.8141626,
     'losses/train_total_loss': 3.1102374}
W1226 00:11:46.937725 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 32800, expected updated value to be 32900, but it was 33000.
I1226 00:11:46.938553 140207281448576 controller.py:457] train | step:  33000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00015624119,
     'losses/train_center_loss': 0.09634447,
     'losses/train_regression_loss': 1.1748358,
     'losses/train_semantic_loss': 1.8163103,
     'losses/train_total_loss': 3.0874906}
I1226 00:11:54.959210 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-33000.
W1226 00:24:39.095309 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 33000, expected updated value to be 33100, but it was 33200.
I1226 00:24:39.096148 140207281448576 controller.py:457] train | step:  33200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00015221779,
     'losses/train_center_loss': 0.09170899,
     'losses/train_regression_loss': 1.1513023,
     'losses/train_semantic_loss': 1.7862518,
     'losses/train_total_loss': 3.0292628}
W1226 00:37:21.999002 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 33200, expected updated value to be 33300, but it was 33400.
I1226 00:37:21.999867 140207281448576 controller.py:457] train | step:  33400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00014818249,
     'losses/train_center_loss': 0.09754038,
     'losses/train_regression_loss': 1.1588331,
     'losses/train_semantic_loss': 1.7749321,
     'losses/train_total_loss': 3.0313056}
W1226 00:50:07.074183 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 33400, expected updated value to be 33500, but it was 33600.
I1226 00:50:07.075065 140207281448576 controller.py:457] train | step:  33600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00014413496,
     'losses/train_center_loss': 0.097746156,
     'losses/train_regression_loss': 1.131235,
     'losses/train_semantic_loss': 1.762536,
     'losses/train_total_loss': 2.9915175}
W1226 01:02:51.526473 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 33600, expected updated value to be 33700, but it was 33800.
I1226 01:02:51.527471 140207281448576 controller.py:457] train | step:  33800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0001400747,
     'losses/train_center_loss': 0.095749244,
     'losses/train_regression_loss': 1.1593919,
     'losses/train_semantic_loss': 1.7839681,
     'losses/train_total_loss': 3.0391095}
W1226 01:15:32.842915 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 33800, expected updated value to be 33900, but it was 34000.
I1226 01:15:32.843776 140207281448576 controller.py:457] train | step:  34000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00013600138,
     'losses/train_center_loss': 0.095884606,
     'losses/train_regression_loss': 1.1450586,
     'losses/train_semantic_loss': 1.7913214,
     'losses/train_total_loss': 3.032265}
I1226 01:15:41.227314 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-34000.
W1226 01:28:24.158157 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 34000, expected updated value to be 34100, but it was 34200.
I1226 01:28:24.158980 140207281448576 controller.py:457] train | step:  34200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00013191446,
     'losses/train_center_loss': 0.099591434,
     'losses/train_regression_loss': 1.1421406,
     'losses/train_semantic_loss': 1.7949992,
     'losses/train_total_loss': 3.036731}
W1226 01:41:11.181259 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 34200, expected updated value to be 34300, but it was 34400.
I1226 01:41:11.182135 140207281448576 controller.py:457] train | step:  34400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00012781343,
     'losses/train_center_loss': 0.08931612,
     'losses/train_regression_loss': 1.1299806,
     'losses/train_semantic_loss': 1.7568793,
     'losses/train_total_loss': 2.9761763}
W1226 01:53:55.097925 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 34400, expected updated value to be 34500, but it was 34600.
I1226 01:53:55.099210 140207281448576 controller.py:457] train | step:  34600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0001236977,
     'losses/train_center_loss': 0.09242866,
     'losses/train_regression_loss': 1.1375587,
     'losses/train_semantic_loss': 1.7864918,
     'losses/train_total_loss': 3.0164783}
W1226 02:06:38.747576 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 34600, expected updated value to be 34700, but it was 34800.
I1226 02:06:38.748420 140207281448576 controller.py:457] train | step:  34800 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00011956671,
     'losses/train_center_loss': 0.08980965,
     'losses/train_regression_loss': 1.1398976,
     'losses/train_semantic_loss': 1.7720153,
     'losses/train_total_loss': 3.0017223}
W1226 02:19:25.661624 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 34800, expected updated value to be 34900, but it was 35000.
I1226 02:19:25.662474 140207281448576 controller.py:457] train | step:  35000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0001154198,
     'losses/train_center_loss': 0.09356791,
     'losses/train_regression_loss': 1.1434093,
     'losses/train_semantic_loss': 1.7357692,
     'losses/train_total_loss': 2.9727466}
I1226 02:19:37.458367 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-35000.
W1226 02:32:24.677268 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 35000, expected updated value to be 35100, but it was 35200.
I1226 02:32:24.678224 140207281448576 controller.py:457] train | step:  35200 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00011125627,
     'losses/train_center_loss': 0.09039447,
     'losses/train_regression_loss': 1.1356398,
     'losses/train_semantic_loss': 1.7588933,
     'losses/train_total_loss': 2.9849274}
W1226 02:45:14.194751 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 35200, expected updated value to be 35300, but it was 35400.
I1226 02:45:14.247704 140207281448576 controller.py:457] train | step:  35400 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00010707531,
     'losses/train_center_loss': 0.14416738,
     'losses/train_regression_loss': 1.3972152,
     'losses/train_semantic_loss': 2.0715673,
     'losses/train_total_loss': 3.6129498}
W1226 02:57:58.881300 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 35400, expected updated value to be 35500, but it was 35600.
I1226 02:57:58.882160 140207281448576 controller.py:457] train | step:  35600 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.00010287616,
     'losses/train_center_loss': 0.13644858,
     'losses/train_regression_loss': 1.3400186,
     'losses/train_semantic_loss': 2.1017504,
     'losses/train_total_loss': 3.5782177}
W1226 03:10:41.151167 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 35600, expected updated value to be 35700, but it was 35800.
I1226 03:10:41.152031 140207281448576 controller.py:457] train | step:  35800 | steps/sec:    0.3 | output: 
    {'learning_rate': 9.8657874e-05,
     'losses/train_center_loss': 0.10347655,
     'losses/train_regression_loss': 1.1933243,
     'losses/train_semantic_loss': 1.8609096,
     'losses/train_total_loss': 3.1577108}
W1226 03:23:28.813145 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 35800, expected updated value to be 35900, but it was 36000.
I1226 03:23:28.814029 140207281448576 controller.py:457] train | step:  36000 | steps/sec:    0.3 | output: 
    {'learning_rate': 9.441945e-05,
     'losses/train_center_loss': 0.10279159,
     'losses/train_regression_loss': 1.1939319,
     'losses/train_semantic_loss': 1.8494114,
     'losses/train_total_loss': 3.1461346}
I1226 03:23:36.430099 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-36000.
W1226 03:36:16.928198 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 36000, expected updated value to be 36100, but it was 36200.
I1226 03:36:16.929055 140207281448576 controller.py:457] train | step:  36200 | steps/sec:    0.3 | output: 
    {'learning_rate': 9.015974e-05,
     'losses/train_center_loss': 0.09564529,
     'losses/train_regression_loss': 1.1569793,
     'losses/train_semantic_loss': 1.7707989,
     'losses/train_total_loss': 3.0234232}
W1226 03:49:02.439317 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 36200, expected updated value to be 36300, but it was 36400.
I1226 03:49:02.440192 140207281448576 controller.py:457] train | step:  36400 | steps/sec:    0.3 | output: 
    {'learning_rate': 8.58775e-05,
     'losses/train_center_loss': 0.09057447,
     'losses/train_regression_loss': 1.1426983,
     'losses/train_semantic_loss': 1.768093,
     'losses/train_total_loss': 3.0013664}
W1226 04:01:42.944378 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 36400, expected updated value to be 36500, but it was 36600.
I1226 04:01:42.945266 140207281448576 controller.py:457] train | step:  36600 | steps/sec:    0.3 | output: 
    {'learning_rate': 8.157146e-05,
     'losses/train_center_loss': 0.088085175,
     'losses/train_regression_loss': 1.1310571,
     'losses/train_semantic_loss': 1.7552768,
     'losses/train_total_loss': 2.9744194}
W1226 04:14:27.674480 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 36600, expected updated value to be 36700, but it was 36800.
I1226 04:14:27.675453 140207281448576 controller.py:457] train | step:  36800 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.723998e-05,
     'losses/train_center_loss': 0.08809964,
     'losses/train_regression_loss': 1.1304703,
     'losses/train_semantic_loss': 1.7453636,
     'losses/train_total_loss': 2.9639335}
W1226 04:27:09.230749 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 36800, expected updated value to be 36900, but it was 37000.
I1226 04:27:09.253562 140207281448576 controller.py:457] train | step:  37000 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.288135e-05,
     'losses/train_center_loss': 0.08678348,
     'losses/train_regression_loss': 1.1250302,
     'losses/train_semantic_loss': 1.7407348,
     'losses/train_total_loss': 2.9525487}
I1226 04:27:16.884968 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-37000.
W1226 04:39:59.481383 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 37000, expected updated value to be 37100, but it was 37200.
I1226 04:39:59.482223 140207281448576 controller.py:457] train | step:  37200 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.849351e-05,
     'losses/train_center_loss': 0.08693733,
     'losses/train_regression_loss': 1.1404283,
     'losses/train_semantic_loss': 1.7486457,
     'losses/train_total_loss': 2.9760113}
W1226 04:52:45.833323 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 37200, expected updated value to be 37300, but it was 37400.
I1226 04:52:45.834160 140207281448576 controller.py:457] train | step:  37400 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.4074215e-05,
     'losses/train_center_loss': 0.085049056,
     'losses/train_regression_loss': 1.1295922,
     'losses/train_semantic_loss': 1.7189813,
     'losses/train_total_loss': 2.9336214}
W1226 05:05:30.188729 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 37400, expected updated value to be 37500, but it was 37600.
I1226 05:05:30.189571 140207281448576 controller.py:457] train | step:  37600 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.9620757e-05,
     'losses/train_center_loss': 0.088601045,
     'losses/train_regression_loss': 1.125793,
     'losses/train_semantic_loss': 1.7517915,
     'losses/train_total_loss': 2.9661853}
W1226 05:18:08.424972 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 37600, expected updated value to be 37700, but it was 37800.
I1226 05:18:08.425791 140207281448576 controller.py:457] train | step:  37800 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.5129974e-05,
     'losses/train_center_loss': 0.08630552,
     'losses/train_regression_loss': 1.0995836,
     'losses/train_semantic_loss': 1.7317739,
     'losses/train_total_loss': 2.9176633}
W1226 05:30:55.018924 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 37800, expected updated value to be 37900, but it was 38000.
I1226 05:30:55.019821 140207281448576 controller.py:457] train | step:  38000 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.059813e-05,
     'losses/train_center_loss': 0.08365011,
     'losses/train_regression_loss': 1.117107,
     'losses/train_semantic_loss': 1.7542535,
     'losses/train_total_loss': 2.955011}
I1226 05:31:02.599929 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-38000.
W1226 05:43:44.597257 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 38000, expected updated value to be 38100, but it was 38200.
I1226 05:43:44.598242 140207281448576 controller.py:457] train | step:  38200 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.6020643e-05,
     'losses/train_center_loss': 0.087132685,
     'losses/train_regression_loss': 1.1436336,
     'losses/train_semantic_loss': 1.7860266,
     'losses/train_total_loss': 3.0167933}
W1226 05:56:24.295701 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 38200, expected updated value to be 38300, but it was 38400.
I1226 05:56:24.296574 140207281448576 controller.py:457] train | step:  38400 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.1391908e-05,
     'losses/train_center_loss': 0.085920125,
     'losses/train_regression_loss': 1.1030728,
     'losses/train_semantic_loss': 1.7155188,
     'losses/train_total_loss': 2.9045112}
W1226 06:09:11.482187 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 38400, expected updated value to be 38500, but it was 38600.
I1226 06:09:11.483055 140207281448576 controller.py:457] train | step:  38600 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.6704794e-05,
     'losses/train_center_loss': 0.08137811,
     'losses/train_regression_loss': 1.1005385,
     'losses/train_semantic_loss': 1.6877557,
     'losses/train_total_loss': 2.8696725}
W1226 06:21:54.626989 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 38600, expected updated value to be 38700, but it was 38800.
I1226 06:21:54.627861 140207281448576 controller.py:457] train | step:  38800 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.1949938e-05,
     'losses/train_center_loss': 0.08480576,
     'losses/train_regression_loss': 1.1079876,
     'losses/train_semantic_loss': 1.7802371,
     'losses/train_total_loss': 2.973031}
W1226 06:34:39.661689 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 38800, expected updated value to be 38900, but it was 39000.
I1226 06:34:39.662529 140207281448576 controller.py:457] train | step:  39000 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.7114835e-05,
     'losses/train_center_loss': 0.08872997,
     'losses/train_regression_loss': 1.1096764,
     'losses/train_semantic_loss': 1.7454165,
     'losses/train_total_loss': 2.9438233}
I1226 06:34:47.609477 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-39000.
W1226 06:47:34.117630 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 39000, expected updated value to be 39100, but it was 39200.
I1226 06:47:34.118481 140207281448576 controller.py:457] train | step:  39200 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.2181348e-05,
     'losses/train_center_loss': 0.10256887,
     'losses/train_regression_loss': 1.1677127,
     'losses/train_semantic_loss': 1.8156815,
     'losses/train_total_loss': 3.0859632}
W1226 07:00:13.839492 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 39200, expected updated value to be 39300, but it was 39400.
I1226 07:00:13.840340 140207281448576 controller.py:457] train | step:  39400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.7121549e-05,
     'losses/train_center_loss': 0.08976181,
     'losses/train_regression_loss': 1.1152024,
     'losses/train_semantic_loss': 1.741072,
     'losses/train_total_loss': 2.946037}
W1226 07:13:03.391260 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 39400, expected updated value to be 39500, but it was 39600.
I1226 07:13:03.392109 140207281448576 controller.py:457] train | step:  39600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.1886688e-05,
     'losses/train_center_loss': 0.083083585,
     'losses/train_regression_loss': 1.0998001,
     'losses/train_semantic_loss': 1.7067053,
     'losses/train_total_loss': 2.8895893}
W1226 07:25:50.620339 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 39600, expected updated value to be 39700, but it was 39800.
I1226 07:25:50.621293 140207281448576 controller.py:457] train | step:  39800 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.3699204e-06,
     'losses/train_center_loss': 0.08235686,
     'losses/train_regression_loss': 1.0993,
     'losses/train_semantic_loss': 1.7177031,
     'losses/train_total_loss': 2.8993592}
W1226 07:38:34.682294 140207281448576 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 39800, expected updated value to be 39900, but it was 40000.
I1226 07:38:34.702715 140207281448576 controller.py:457] train | step:  40000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0,
     'losses/train_center_loss': 0.07923039,
     'losses/train_regression_loss': 1.0919,
     'losses/train_semantic_loss': 1.6768155,
     'losses/train_total_loss': 2.8479455}
I1226 07:38:42.323911 140207281448576 controller.py:486] saved checkpoint to ../model_dir/ckpt-40000.
